// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinMerchantAppConfig is the golang structure of table weixin_merchant_app_config for DAO operations like Where/Data.
type WeixinMerchantAppConfig struct {
	g.Meta       `orm:"table:weixin_merchant_app_config, do:true"`
	Id           interface{} // 授权商家id
	Name         interface{} // 授权商家name
	AppId        interface{} // 商家授权应用Id
	AppName      interface{} // 商家授权应用名称
	AppType      interface{} // 应用类型
	AppAuthToken interface{} // 授权应用token
	IsFullProxy  interface{} // 是否全权委托待开发：0否 1是
	AuthState    interface{} // 授权状态
	ExpiresIn    *gtime.Time // 生效时间
	ReExpiresIn  *gtime.Time // 失效时间
	UserId       interface{} // 用户账号id
	UnionMainId  interface{} // 关联主体id
	SysUserId    interface{} // 用户id
	Tokens       interface{} // token列表
	ExtJson      interface{} // 拓展字段
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
	DeletedAt    *gtime.Time //
}
