// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package weixin_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinConsumerConfig is the golang structure of table weixin_consumer_config for DAO operations like Where/Data.
type WeixinConsumerConfig struct {
	g.Meta             `orm:"table:weixin_consumer_config, do:true"`
	Id                 interface{} // id
	OpenId             interface{} // 微信用户openId，不同应用下的用户具备不同的openId
	SysUserId          interface{} // 用户id
	Avatar             interface{} // 头像
	Province           interface{} // 省份
	City               interface{} // 城市
	NickName           interface{} // 昵称
	IsStudentCertified interface{} // 是否学生认证
	UserType           interface{} // 用户账号类型，和sysUserType保持一致
	UserState          interface{} // 状态：0未激活、1正常、-1封号、-2异常、-3已注销
	IsCertified        interface{} // 是否实名认证
	Sex                interface{} // 性别：0女 1男
	AccessToken        interface{} // 授权token
	ExtJson            interface{} // 拓展字段
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
	DeletedAt          *gtime.Time //
	UnionId            interface{} // 微信用户union_id，同一个开放平台帐号下的用户只有一个unionId
	SessionKey         interface{} // 微信用户会话key
	RefreshToken       interface{} // 用户授权刷新令牌
	ExpiresIn          *gtime.Time // 令牌过期时间
	AuthState          interface{} // 微信用户授权状态：1已授权、2未授权
	AppType            interface{} // 应用类型：1公众号 2小程序 4网站应用H5  8移动应用  16视频小店
	IsFollowPublic     interface{} // 是否关注公众号：1关注、2未关注
	AppId              interface{} // 商家应用Id
}
