// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package weixin_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinSubscribeMessageTemplate is the golang structure of table weixin_subscribe_message_template for DAO operations like Where/Data.
type WeixinSubscribeMessageTemplate struct {
	g.Meta                   `orm:"table:weixin_subscribe_message_template, do:true"`
	Id                       interface{} // ID
	TemplateId               interface{} // 模板ID
	Type                     interface{} // 模板类型：2一次性订阅、3长期订阅
	Title                    interface{} // 模板标题
	KeyWords                 interface{} // 模板主题词/关键词
	ServerCategory           interface{} // 模板服务类目
	ServerCategoryId         interface{} // 模板服务类目ID
	Content                  interface{} // 模板内容
	ContentExample           interface{} // 模板内容示例
	ContentDataJson          interface{} // 模板内容Json
	KeyWordEnumValueListJson interface{} // 模板枚举参数值范围列表
	SceneDesc                interface{} // 场景描述
	SceneType                interface{} // 场景类型【业务层自定义】：1活动即将开始提醒、2活动开始提醒、3活动即将结束提醒、4活动结束提醒、5活动获奖提醒、6券即将生效提醒、7券的生效提醒、8券的失效提醒、9券即将失效提醒、10券核销提醒、8192系统通知、
	MessageType              interface{} // 消息类型【业务层自定义】：1系统消息、2活动消息、4免啦券消息
	MerchantAppId            interface{} // 商家应用APPID
	MerchantAppType          interface{} // 商家应用类型：1公众号、2小程序、4网站应用H5、8移动应用、16视频小店
	ThirdAppId               interface{} // 第三方平台应用APPID
	UserId                   interface{} // 应用所属账号
	UnionMainId              interface{} // 关联主体id
	ExtJson                  interface{} // 拓展字段Json
	CreatedAt                *gtime.Time //
	UpdatedAt                *gtime.Time //
}
