// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinPaySubMerchant is the golang structure of table weixin_pay_sub_merchant for DAO operations like Where/Data.
type WeixinPaySubMerchant struct {
	g.Meta               `orm:"table:weixin_pay_sub_merchant, do:true"`
	Id                   interface{} // ID
	SubMchid             interface{} // 特约商户商户号
	SpMchid              interface{} // 服务商商户号
	SubAppid             interface{} // 特约商户App唯一标识ID
	SubAppName           interface{} // 特约商户App名称
	SubAppType           interface{} // 特约商户App类型：1公众号 2小程序 4网站应用H5  8移动应用  16视频小店
	SubMerchantName      interface{} // 特约商户公司名称
	SubMerchantShortName interface{} // 特约商户商家简称
	SysUserId            interface{} // 特约商户用户ID
	UnionMainId          interface{} // 特约商户用户主体
	UnionMainType        interface{} // 特约商户主体类型
	JsapiAuthPath        interface{} // JSAPI支付授权目录
	H5AuthPath           interface{} // H5支付授权目录
	UpdatedAt            *gtime.Time //
}
