// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weixin_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

type PlatformUserDao = dao_interface.TIDao[internal.PlatformUserColumns]

func NewPlatformUser(dao ...dao_interface.IDao) PlatformUserDao {
	return (PlatformUserDao)(internal.NewPlatformUserDao(dao...))
}

var (
	PlatformUser = NewPlatformUser()
)
