// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weixin_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

type WeixinThirdAppConfigDao = dao_interface.TIDao[internal.WeixinThirdAppConfigColumns]

func NewWeixinThirdAppConfig(dao ...dao_interface.IDao) WeixinThirdAppConfigDao {
	return (WeixinThirdAppConfigDao)(internal.NewWeixinThirdAppConfigDao(dao...))
}

var (
	WeixinThirdAppConfig = NewWeixinThirdAppConfig()
)
