// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

// internalWeixinPaySubMerchantDao is internal type for wrapping internal DAO implements.
type internalWeixinPaySubMerchantDao = *internal.WeixinPaySubMerchantDao

// weixinPaySubMerchantDao is the data access object for table weixin_pay_sub_merchant.
// You can define custom methods on it to extend its functionality as you wish.
type weixinPaySubMerchantDao struct {
	internalWeixinPaySubMerchantDao
}

var (
	// WeixinPaySubMerchant is globally public accessible object for table weixin_pay_sub_merchant operations.
	WeixinPaySubMerchant = weixinPaySubMerchantDao{
		internal.NewWeixinPaySubMerchantDao(),
	}
)

// Fill with you ideas below.
