// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weixin_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

type WeixinPaySubMerchantDao = dao_interface.TIDao[internal.WeixinPaySubMerchantColumns]

func NewWeixinPaySubMerchant(dao ...dao_interface.IDao) WeixinPaySubMerchantDao {
	return (WeixinPaySubMerchantDao)(internal.NewWeixinPaySubMerchantDao(dao...))
}

var (
	WeixinPaySubMerchant = NewWeixinPaySubMerchant()
)
