// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weixin_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

type WeixinMerchantAppConfigDao = dao_interface.TIDao[internal.WeixinMerchantAppConfigColumns]

func NewWeixinMerchantAppConfig(dao ...dao_interface.IDao) WeixinMerchantAppConfigDao {
	return (WeixinMerchantAppConfigDao)(internal.NewWeixinMerchantAppConfigDao(dao...))
}

var (
	WeixinMerchantAppConfig = NewWeixinMerchantAppConfig()
)
