// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package weixin_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

type WeixinConsumerConfigDao = dao_interface.TIDao[internal.WeixinConsumerConfigColumns]

func NewWeixinConsumerConfig(dao ...dao_interface.IDao) WeixinConsumerConfigDao {
	return (WeixinConsumerConfigDao)(internal.NewWeixinConsumerConfigDao(dao...))
}

var (
	WeixinConsumerConfig = NewWeixinConsumerConfig()
)
