// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

// internalWeixinPayMerchantDao is internal type for wrapping internal DAO implements.
type internalWeixinPayMerchantDao = *internal.WeixinPayMerchantDao

// weixinPayMerchantDao is the data access object for table weixin_pay_merchant.
// You can define custom methods on it to extend its functionality as you wish.
type weixinPayMerchantDao struct {
	internalWeixinPayMerchantDao
}

var (
	// WeixinPayMerchant is globally public accessible object for table weixin_pay_merchant operations.
	WeixinPayMerchant = weixinPayMerchantDao{
		internal.NewWeixinPayMerchantDao(),
	}
)

// Fill with you ideas below.
