// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kysion/weixin-library/weixin_model/weixin_dao/internal"
)

// internalWeixinConsumerConfigDao is internal type for wrapping internal DAO implements.
type internalWeixinConsumerConfigDao = *internal.WeixinConsumerConfigDao

// weixinConsumerConfigDao is the data access object for table weixin_consumer_config.
// You can define custom methods on it to extend its functionality as you wish.
type weixinConsumerConfigDao struct {
	internalWeixinConsumerConfigDao
}

var (
	// WeixinConsumerConfig is globally public accessible object for table weixin_consumer_config operations.
	WeixinConsumerConfig = weixinConsumerConfigDao{
		internal.NewWeixinConsumerConfigDao(),
	}
)

// Fill with you ideas below.
