// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/kysion/kys-weixin-library/weixin_model/weixin_dao/internal"
)

// internalWeixinMerchantAppConfigDao is internal type for wrapping internal DAO implements.
type internalWeixinMerchantAppConfigDao = *internal.WeixinMerchantAppConfigDao

// weixinMerchantAppConfigDao is the data access object for table weixin_merchant_app_config.
// You can define custom methods on it to extend its functionality as you wish.
type weixinMerchantAppConfigDao struct {
	internalWeixinMerchantAppConfigDao
}

var (
	// WeixinMerchantAppConfig is globally public accessible object for table weixin_merchant_app_config operations.
	WeixinMerchantAppConfig = weixinMerchantAppConfigDao{
		internal.NewWeixinMerchantAppConfigDao(),
	}
)

// Fill with you ideas below.
