// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/kysion/weixin-library/internal/logic/gateway"
	_ "github.com/kysion/weixin-library/internal/logic/merchant"
	_ "github.com/kysion/weixin-library/internal/logic/third_app_service"
)
