// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. {TplCreatedAtDatetimeStr}
// =================================================================================

package weixin_entity

{TplPackageImports}

// {TplTableNameCamelCase} is the golang structure for table {TplTableName}.
{TplStructDefine}
