

# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "kys-weixin-library"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - link: "pgsql:user=kuaimk password=Kuaimk23db host=192.168.1.105 port=5432 dbname=kuaimk_test sslmode=disable"
        # link: "pgsql:user=kysion password=kysiondb host=182.43.195.225 port=15432 dbname=gf-admin sslmode=disable"
        tables: "merchant_app_config, consumer_config, third_app_config"
        descriptionTag:  true
        noModelComment:  true
        withTime: false
