

# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  # 工具编译配置
  build:
    name:     "weixin-library"
    arch:     "amd64"
    system:   "linux,darwin,windows"
    mod:      ""
    cgo:      0

  # dao生成
  gen:
    dao:
      - #link: : "pgsql:user=root password=root host=127.0.0.1 port=5432 dbname=test sslmode=disable"
        link: "pgsql:user=kuaimk password=Kuaimk23db host=192.168.1.105 port=5432 dbname=kmk_struct sslmode=disable"
        # link: "pgsql:user=kysion password=kysiondb host=182.43.195.225 port=15432 dbname=gf-admin sslmode=disable"
        tables: "weixin_merchant_app_config, weixin_consumer_config, weixin_third_app_config, platform_user, weixin_pay_merchant, weixin_pay_sub_merchant "
        descriptionTag:  true
        noModelComment:  true
        withTime: false
