// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package weixin_service

import (
	"context"

	"github.com/gogf/gf/v2/frame/g"
)

type (
	IAppAuth interface {
		AppAuth(ctx context.Context, info g.Map) bool
		Authorized(ctx context.Context, info g.Map) bool
		UpdateAuthorized(ctx context.Context, info g.Map) bool
		Unauthorized(ctx context.Context, info g.Map) bool
	}
	IUserAuth interface{}
)

var (
	localAppAuth  IAppAuth
	localUserAuth IUserAuth
)

func AppAuth() IAppAuth {
	if localAppAuth == nil {
		panic("implement not found for interface IAppAuth, forgot register?")
	}
	return localAppAuth
}

func RegisterAppAuth(i IAppAuth) {
	localAppAuth = i
}

func UserAuth() IUserAuth {
	if localUserAuth == nil {
		panic("implement not found for interface IUserAuth, forgot register?")
	}
	return localUserAuth
}

func RegisterUserAuth(i IUserAuth) {
	localUserAuth = i
}
