// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package weixin_service

import (
	"context"

	"github.com/kysion/kys-weixin-library/weixin_model"
)

type (
	IWeiXin interface {
		UserInfoAuth(ctx context.Context) (string, error)
		WeiXinServices(ctx context.Context, eventInfo *weixin_model.EventEncryptMsgReq, msgInfo *weixin_model.MessageEncryptReq) (string, error)
		WeiXinCallback(ctx context.Context) (string, error)
		WXCheckSignature(ctx context.Context, signature, timestamp, nonce, echostr string) string
	}
)

var (
	localWeiXin IWeiXin
)

func WeiXin() IWeiXin {
	if localWeiXin == nil {
		panic("implement not found for interface IWeiXin, forgot register?")
	}
	return localWeiXin
}

func RegisterWeiXin(i IWeiXin) {
	localWeiXin = i
}
