// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PlatformUserDao is the data access object for table platform_user.
type PlatformUserDao struct {
	table   string              // table is the underlying table name of the DAO.
	group   string              // group is the database configuration group name of current DAO.
	columns PlatformUserColumns // columns contains all the column names of Table for convenient usage.
}

// PlatformUserColumns defines and stores column names for table platform_user.
type PlatformUserColumns struct {
	Id            string //
	FacilitatorId string // 服务商id
	OperatorId    string // 运营商id
	MerchantId    string // 商户id
	EmployeeId    string // 员工id
	Platform      string // 平台类型：1支付宝、2微信、4抖音、8银联
	ThirdAppId    string // 第三方平台AppId
	MerchantAppId string // 商家应用AppId
	CreatedAt     string //
	UpdatedAt     string //
	UserId        string // 平台用户唯一标识
	Type          string // 用户类型：0匿名，1用户，2微商，4商户、8广告主、16服务商、32运营中心，64后台
}

// platformUserColumns holds the columns for table platform_user.
var platformUserColumns = PlatformUserColumns{
	Id:            "id",
	FacilitatorId: "facilitator_id",
	OperatorId:    "operator_id",
	MerchantId:    "merchant_id",
	EmployeeId:    "employee_id",
	Platform:      "platform",
	ThirdAppId:    "third_app_id",
	MerchantAppId: "merchant_app_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	UserId:        "user_id",
	Type:          "type",
}

// NewPlatformUserDao creates and returns a new DAO object for table data access.
func NewPlatformUserDao(proxy ...dao_interface.IDao) *PlatformUserDao {
	var dao *PlatformUserDao
	if len(proxy) > 0 {
		dao = &PlatformUserDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: platformUserColumns,
		}
		return dao
	}

	return &PlatformUserDao{
		group:   "default",
		table:   "platform_user",
		columns: platformUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PlatformUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PlatformUserDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *PlatformUserDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *PlatformUserDao) Columns() PlatformUserColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PlatformUserDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *PlatformUserDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PlatformUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
