// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WeixinConsumerConfigDao is the data access object for table weixin_consumer_config.
type WeixinConsumerConfigDao struct {
	dao_interface.IDao
	table       string                      // table is the underlying table name of the DAO.
	group       string                      // group is the database configuration group name of current DAO.
	columns     WeixinConsumerConfigColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// WeixinConsumerConfigColumns defines and stores column names for table weixin_consumer_config.
type WeixinConsumerConfigColumns struct {
	Id                 string // id
	OpenId             string // 微信用户openId，不同应用下的用户具备不同的openId
	SysUserId          string // 用户id
	Avatar             string // 头像
	Province           string // 省份
	City               string // 城市
	NickName           string // 昵称
	IsStudentCertified string // 是否学生认证
	UserType           string // 用户账号类型，和sysUserType保持一致
	UserState          string // 状态：0未激活、1正常、-1封号、-2异常、-3已注销
	IsCertified        string // 是否实名认证
	Sex                string // 性别：0未知、1男、2女
	AccessToken        string // 授权token
	ExtJson            string // 拓展字段
	CreatedAt          string //
	UpdatedAt          string //
	DeletedAt          string //
	UnionId            string // 微信用户union_id，同一个开放平台帐号下的用户只有一个unionId
	SessionKey         string // 微信用户会话key
	RefreshToken       string // 用户授权刷新令牌
	ExpiresIn          string // 令牌过期时间
	AuthState          string // 微信用户授权状态：1已授权、2未授权
	AppType            string // 应用类型：1公众号 2小程序 4网站应用H5  8移动应用  16视频小店
	IsFollowPublic     string // 是否关注公众号：1关注、2未关注
	AppId              string // 商家应用Id
}

// weixinConsumerConfigColumns holds the columns for table weixin_consumer_config.
var weixinConsumerConfigColumns = WeixinConsumerConfigColumns{
	Id:                 "id",
	OpenId:             "open_id",
	SysUserId:          "sys_user_id",
	Avatar:             "avatar",
	Province:           "province",
	City:               "city",
	NickName:           "nick_name",
	IsStudentCertified: "is_student_certified",
	UserType:           "user_type",
	UserState:          "user_state",
	IsCertified:        "is_certified",
	Sex:                "sex",
	AccessToken:        "access_token",
	ExtJson:            "ext_json",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
	DeletedAt:          "deleted_at",
	UnionId:            "union_id",
	SessionKey:         "session_key",
	RefreshToken:       "refresh_token",
	ExpiresIn:          "expires_in",
	AuthState:          "auth_state",
	AppType:            "app_type",
	IsFollowPublic:     "is_follow_public",
	AppId:              "app_id",
}

// NewWeixinConsumerConfigDao creates and returns a new DAO object for table data access.
func NewWeixinConsumerConfigDao(proxy ...dao_interface.IDao) *WeixinConsumerConfigDao {
	var dao *WeixinConsumerConfigDao
	if len(proxy) > 0 {
		dao = &WeixinConsumerConfigDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     weixinConsumerConfigColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &WeixinConsumerConfigDao{
		group:   "default",
		table:   "weixin_consumer_config",
		columns: weixinConsumerConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WeixinConsumerConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WeixinConsumerConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *WeixinConsumerConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *WeixinConsumerConfigDao) Columns() WeixinConsumerConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WeixinConsumerConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *WeixinConsumerConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WeixinConsumerConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *WeixinConsumerConfigDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *WeixinConsumerConfigDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *WeixinConsumerConfigDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *WeixinConsumerConfigDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
