// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WeixinMerchantAppConfigDao is the data access object for table weixin_merchant_app_config.
type WeixinMerchantAppConfigDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns WeixinMerchantAppConfigColumns // columns contains all the column names of Table for convenient usage.
}

// WeixinMerchantAppConfigColumns defines and stores column names for table weixin_merchant_app_config.
type WeixinMerchantAppConfigColumns struct {
	Id             string // 商家id
	Name           string // 商家name
	AppId          string // 商家应用Id
	AppName        string // 商家应用名称
	AppType        string // 应用类型：1公众号 2小程序 4网站应用H5  8移动应用  16视频小店
	AppAuthToken   string // 应用token
	IsFullProxy    string // 是否全权委托待开发：0否 1是
	State          string // 状态： 0禁用 1启用
	ExpiresIn      string // Token过期时间
	ReExpiresIn    string // Token限期刷新时间
	UserId         string // 用户账号id
	UnionMainId    string // 关联主体id
	SysUserId      string // 用户id
	ExtJson        string // 拓展字段
	AppGatewayUrl  string // 网关地址
	AppCallbackUrl string // 回调地址
	AppSecret      string // 服务器应用密钥
	MsgVerfiyToken string // 消息校验Token
	MsgEncryptKey  string // 消息加密解密密钥
	MsgEncryptType string // 消息加密模式：1兼容模式 2明文模式 4安全模式
	BusinessDomain string // 业务域名
	JsDomain       string // JS接口安全域名
	AuthDomain     string // 网页授权域名
	Logo           string // 商家logo
	HttpsCert      string // 域名证书
	HttpsKey       string // 域名私钥
}

// weixinMerchantAppConfigColumns holds the columns for table weixin_merchant_app_config.
var weixinMerchantAppConfigColumns = WeixinMerchantAppConfigColumns{
	Id:             "id",
	Name:           "name",
	AppId:          "app_id",
	AppName:        "app_name",
	AppType:        "app_type",
	AppAuthToken:   "app_auth_token",
	IsFullProxy:    "is_full_proxy",
	State:          "state",
	ExpiresIn:      "expires_in",
	ReExpiresIn:    "re_expires_in",
	UserId:         "user_id",
	UnionMainId:    "union_main_id",
	SysUserId:      "sys_user_id",
	ExtJson:        "ext_json",
	AppGatewayUrl:  "app_gateway_url",
	AppCallbackUrl: "app_callback_url",
	AppSecret:      "app_secret",
	MsgVerfiyToken: "msg_verfiy_token",
	MsgEncryptKey:  "msg_encrypt_key",
	MsgEncryptType: "msg_encrypt_type",
	BusinessDomain: "business_domain",
	JsDomain:       "js_domain",
	AuthDomain:     "auth_domain",
	Logo:           "logo",
	HttpsCert:      "https_cert",
	HttpsKey:       "https_key",
}

// NewWeixinMerchantAppConfigDao creates and returns a new DAO object for table data access.
func NewWeixinMerchantAppConfigDao(proxy ...dao_interface.IDao) *WeixinMerchantAppConfigDao {
	var dao *WeixinMerchantAppConfigDao
	if proxy != nil {
		dao = &WeixinMerchantAppConfigDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: weixinMerchantAppConfigColumns,
		}
		return dao
	}

	return &WeixinMerchantAppConfigDao{
		group:   "default",
		table:   "weixin_merchant_app_config",
		columns: weixinMerchantAppConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WeixinMerchantAppConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WeixinMerchantAppConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *WeixinMerchantAppConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *WeixinMerchantAppConfigDao) Columns() WeixinMerchantAppConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WeixinMerchantAppConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *WeixinMerchantAppConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WeixinMerchantAppConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
