// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// WeixinMerchantAppConfigDao is the data access object for table weixin_merchant_app_config.
type WeixinMerchantAppConfigDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns WeixinMerchantAppConfigColumns // columns contains all the column names of Table for convenient usage.
}

// WeixinMerchantAppConfigColumns defines and stores column names for table weixin_merchant_app_config.
type WeixinMerchantAppConfigColumns struct {
	Id           string // 授权商家id
	Name         string // 授权商家name
	AppId        string // 商家授权应用Id
	AppName      string // 商家授权应用名称
	AppType      string // 应用类型
	AppAuthToken string // 授权应用token
	IsFullProxy  string // 是否全权委托待开发：0否 1是
	AuthState    string // 授权状态
	ExpiresIn    string // 生效时间
	ReExpiresIn  string // 失效时间
	UserId       string // 用户账号id
	UnionMainId  string // 关联主体id
	SysUserId    string // 用户id
	Tokens       string // token列表
	ExtJson      string // 拓展字段
	CreatedAt    string //
	UpdatedAt    string //
	DeletedAt    string //
}

// weixinMerchantAppConfigColumns holds the columns for table weixin_merchant_app_config.
var weixinMerchantAppConfigColumns = WeixinMerchantAppConfigColumns{
	Id:           "id",
	Name:         "name",
	AppId:        "app_id",
	AppName:      "app_name",
	AppType:      "app_type",
	AppAuthToken: "app_auth_token",
	IsFullProxy:  "is_full_proxy",
	AuthState:    "auth_state",
	ExpiresIn:    "expires_in",
	ReExpiresIn:  "re_expires_in",
	UserId:       "user_id",
	UnionMainId:  "union_main_id",
	SysUserId:    "sys_user_id",
	Tokens:       "tokens",
	ExtJson:      "ext_json",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
	DeletedAt:    "deleted_at",
}

// NewWeixinMerchantAppConfigDao creates and returns a new DAO object for table data access.
func NewWeixinMerchantAppConfigDao(proxy ...dao_interface.IDao) *WeixinMerchantAppConfigDao {
	var dao *WeixinMerchantAppConfigDao
	if proxy != nil {
		dao = &WeixinMerchantAppConfigDao{
			group:   proxy[0].Group(),
			table:   proxy[0].Table(),
			columns: weixinMerchantAppConfigColumns,
		}
		return dao
	}

	return &WeixinMerchantAppConfigDao{
		group:   "default",
		table:   "weixin_merchant_app_config",
		columns: weixinMerchantAppConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *WeixinMerchantAppConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *WeixinMerchantAppConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *WeixinMerchantAppConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *WeixinMerchantAppConfigDao) Columns() WeixinMerchantAppConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *WeixinMerchantAppConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *WeixinMerchantAppConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) dao_interface.DaoConfig {
	daoConfig := dao_interface.DaoConfig{
		Dao:   dao,
		DB:    dao.DB(),
		Table: dao.table,
		Group: dao.group,
		Model: dao.DB().Model(dao.Table()).Safe().Ctx(ctx),
	}

	if len(cacheOption) == 0 {
		daoConfig.CacheOption = daoctl.MakeDaoCache(dao.Table())
		daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
	} else {
		if cacheOption[0] != nil {
			daoConfig.CacheOption = cacheOption[0]
			daoConfig.Model = daoConfig.Model.Cache(*daoConfig.CacheOption)
		}
	}

	daoConfig.Model = daoctl.RegisterDaoHook(daoConfig.Model)

	return daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *WeixinMerchantAppConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
