// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package weixin_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinPaySubMerchant is the golang structure for table weixin_pay_sub_merchant.
type WeixinPaySubMerchant struct {
	Id                   int64       `json:"id"                   orm:"id"                      description:"ID"`
	SubMchid             int         `json:"subMchid"             orm:"sub_mchid"               description:"特约商户商户号"`
	SpMchid              int         `json:"spMchid"              orm:"sp_mchid"                description:"服务商商户号"`
	SubAppid             string      `json:"subAppid"             orm:"sub_appid"               description:"特约商户App唯一标识ID"`
	SubAppName           string      `json:"subAppName"           orm:"sub_app_name"            description:"特约商户App名称"`
	SubAppType           int         `json:"subAppType"           orm:"sub_app_type"            description:"特约商户App类型：1公众号 2小程序 4网站应用H5  8移动应用  16视频小店"`
	SubMerchantName      string      `json:"subMerchantName"      orm:"sub_merchant_name"       description:"特约商户公司名称"`
	SubMerchantShortName string      `json:"subMerchantShortName" orm:"sub_merchant_short_name" description:"特约商户商家简称"`
	SysUserId            int64       `json:"sysUserId"            orm:"sys_user_id"             description:"特约商户用户ID"`
	UnionMainId          int64       `json:"unionMainId"          orm:"union_main_id"           description:"特约商户用户主体"`
	UnionMainType        int         `json:"unionMainType"        orm:"union_main_type"         description:"特约商户主体类型"`
	JsapiAuthPath        string      `json:"jsapiAuthPath"        orm:"jsapi_auth_path"         description:"JSAPI支付授权目录"`
	H5AuthPath           string      `json:"h5AuthPath"           orm:"h5_auth_path"            description:"H5支付授权目录"`
	UpdatedAt            *gtime.Time `json:"updatedAt"            orm:"updated_at"              description:""`
	MerchantType         int         `json:"merchantType"         orm:"merchant_type"           description:"商户号类型：1服务商、2商户、4门店商家"`
	MerchantUnionType    int         `json:"merchantUnionType"    orm:"merchant_union_type"     description:"特约商户主体类型：1个体工商户、2企业、4事业单位、8社会组织、16政府机关"`
	BankcardAccount      string      `json:"bankcardAccount"      orm:"bankcard_account"        description:"结算账号，添加特约商户的时候填写的结算银行账户"`
}
