// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinMerchantAppConfig is the golang structure for table weixin_merchant_app_config.
type WeixinMerchantAppConfig struct {
	Id           int64       `json:"id"           description:"授权商家id"`
	Name         string      `json:"name"         description:"授权商家name"`
	AppId        int64       `json:"appId"        description:"商家授权应用Id"`
	AppName      string      `json:"appName"      description:"商家授权应用名称"`
	AppType      string      `json:"appType"      description:"应用类型"`
	AppAuthToken string      `json:"appAuthToken" description:"授权应用token"`
	IsFullProxy  int         `json:"isFullProxy"  description:"是否全权委托待开发：0否 1是"`
	AuthState    int         `json:"authState"    description:"授权状态"`
	ExpiresIn    *gtime.Time `json:"expiresIn"    description:"生效时间"`
	ReExpiresIn  *gtime.Time `json:"reExpiresIn"  description:"失效时间"`
	UserId       int64       `json:"userId"       description:"用户账号id"`
	UnionMainId  int64       `json:"unionMainId"  description:"关联主体id"`
	SysUserId    int64       `json:"sysUserId"    description:"用户id"`
	Tokens       string      `json:"tokens"       description:"token列表"`
	ExtJson      string      `json:"extJson"      description:"拓展字段"`
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`
	DeletedAt    *gtime.Time `json:"deletedAt"    description:""`
}
