// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package weixin_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinSubscribeMessageTemplate is the golang structure for table weixin_subscribe_message_template.
type WeixinSubscribeMessageTemplate struct {
	Id                       int64       `json:"id"                       orm:"id"                            description:"ID"`
	TemplateId               string      `json:"templateId"               orm:"template_id"                   description:"模板ID"`
	Type                     int         `json:"type"                     orm:"type"                          description:"模板类型：2一次性订阅、3长期订阅"`
	Title                    string      `json:"title"                    orm:"title"                         description:"模板标题"`
	KeyWords                 string      `json:"keyWords"                 orm:"key_words"                     description:"模板主题词/关键词"`
	ServerCategory           string      `json:"serverCategory"           orm:"server_category"               description:"模板服务类目"`
	ServerCategoryId         int         `json:"serverCategoryId"         orm:"server_category_id"            description:"模板服务类目ID"`
	Content                  string      `json:"content"                  orm:"content"                       description:"模板内容"`
	ContentExample           string      `json:"contentExample"           orm:"content_example"               description:"模板内容示例"`
	ContentDataJson          string      `json:"contentDataJson"          orm:"content_data_json"             description:"模板内容Json"`
	KeyWordEnumValueListJson string      `json:"keyWordEnumValueListJson" orm:"key_word_enum_value_list_json" description:"模板枚举参数值范围列表"`
	SceneDesc                string      `json:"sceneDesc"                orm:"scene_desc"                    description:"场景描述"`
	SceneType                int         `json:"sceneType"                orm:"scene_type"                    description:"场景类型【业务层自定义】：1活动即将开始提醒、2活动开始提醒、3活动即将结束提醒、4活动结束提醒、5活动获奖提醒、6券即将生效提醒、7券的生效提醒、8券的失效提醒、9券即将失效提醒、10券核销提醒、8192系统通知、"`
	MessageType              int         `json:"messageType"              orm:"message_type"                  description:"消息类型【业务层自定义】：1系统消息、2活动消息、4免啦券消息"`
	MerchantAppId            string      `json:"merchantAppId"            orm:"merchant_app_id"               description:"商家应用APPID"`
	MerchantAppType          int         `json:"merchantAppType"          orm:"merchant_app_type"             description:"商家应用类型：1公众号、2小程序、4网站应用H5、8移动应用、16视频小店"`
	ThirdAppId               string      `json:"thirdAppId"               orm:"third_app_id"                  description:"第三方平台应用APPID"`
	UserId                   int64       `json:"userId"                   orm:"user_id"                       description:"应用所属账号"`
	UnionMainId              int64       `json:"unionMainId"              orm:"union_main_id"                 description:"关联主体id"`
	ExtJson                  string      `json:"extJson"                  orm:"ext_json"                      description:"拓展字段Json"`
	CreatedAt                *gtime.Time `json:"createdAt"                orm:"created_at"                    description:""`
	UpdatedAt                *gtime.Time `json:"updatedAt"                orm:"updated_at"                    description:""`
}
