// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// WeixinConsumerConfig is the golang structure for table weixin_consumer_config.
type WeixinConsumerConfig struct {
	Id                 int64       `json:"id"                 description:"id"`
	UserId             int64       `json:"userId"             description:"用户账号id"`
	SysUserId          int64       `json:"sysUserId"          description:"用户id"`
	Avatar             string      `json:"avatar"             description:"头像"`
	Province           string      `json:"province"           description:"省份"`
	City               string      `json:"city"               description:"城市"`
	NickName           string      `json:"nickName"           description:"昵称"`
	IsStudentCertified int         `json:"isStudentCertified" description:"学生认证"`
	UserType           string      `json:"userType"           description:"用户账号类型"`
	UserState          int         `json:"userState"          description:"状态：0未激活、1正常、-1封号、-2异常、-3已注销"`
	IsCertified        int         `json:"isCertified"        description:"是否实名认证"`
	Sex                int         `json:"sex"                description:"性别：0女 1男"`
	AuthToken          string      `json:"authToken"          description:"授权token"`
	ExtJson            string      `json:"extJson"            description:"拓展字段"`
	CreatedAt          *gtime.Time `json:"createdAt"          description:""`
	UpdatedAt          *gtime.Time `json:"updatedAt"          description:""`
	DeletedAt          *gtime.Time `json:"deletedAt"          description:""`
}
